# Reusable workflow that builds and pushes/loads images to Nexus
name: Build and Push
on:
  # TODO - a better approach than this
  workflow_dispatch:
    inputs:
      major:
        description: Major version
        required: true
        type: string
      minor:
        description: Minor version
        required: true
        type: string
      patch:
        description: Patch version
        required: true
        type: string
      os:
        description: The OS of the base image
        required: true
        type: choice
        options:
        - ubi8
        - rockylinux
      is_latest:
        description: latest tag
        default: false
        type: boolean
      latest_major:
        description: latest major version
        default: false
        type: boolean
      latest_minor:
        description: latest minor version
        default: false
        type: boolean

# used by the bake file
env:
  MAJOR_VERSION: ${{ inputs.major }}
  MINOR_VERSION: ${{ inputs.minor }}
  PATCH_VERSION: ${{ inputs.patch }}
  OS: ${{ inputs.os }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            jackhrt/fluentd-docker
          tags: |
            type=raw,value=latest-${{ inputs.os }},enable=${{ inputs.is_latest }}
            type=raw,value=v${{ inputs.major }}-${{ inputs.os }},enable=${{ inputs.latest_major }}
            type=raw,value=v${{ inputs.major }}.${{ inputs.minor }}-${{ inputs.os }},enable=${{ inputs.latest_minor }}
            type=raw,value=v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}-${{ inputs.os }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jackhrt
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # TODO - test before pushing
      - name: Build and Push amd64
        uses: docker/bake-action@v2
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: fluentd-prod
          set: |
            *.platform=linux/amd64
      - name: Build and Push arm64
        uses: docker/bake-action@v2
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: fluentd-prod
          set: |
            *.platform=linux/arm64
